### ISSUE TITLE
Should I add R19 to a v0.5 board?

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [elektronomikon/raspi_gpib_shield#1]
I have bought a shield and I got version v0.5. It does not have R19 like [v0.6](https://github.com/elektronomikon/raspi_gpib_shield/blob/master/Documentation/RasPi%20GPIB%20Shield%20V0.6.png).

Is it recommended to add R19?

**Comment by elektronomikon** [comment]
Hi,

adding R19 should not have an impact on the connection with standard compliant devices as it acts as a pull-up on the DAV line which should be driven by the talker.

Thank you for bringing this up, it will be removed in the next version ...

have fun,
Thomas
