### ISSUE TITLE
Assembling instructions: getting the GPIO header right

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [elektronomikon/raspi_gpib_shield#3]
We received some short assembling instructions with the hardware kit, telling which components to be soldered for the active or passive version. Maybe you could add a short note on how to assemble the GPIO header in correct length. Basically:

1. Put the spacers onto the RPi
2. Fit the GPIO connector onto the RPi
3. Place the PCB onto the spacers
4. Solder the GPIO connector while having the correct distance

Solder the GPIO header when having it in this position:

![grafik](https://user-images.githubusercontent.com/25632350/93871819-894a5000-fccf-11ea-94da-250d2e0658b0.png)

If not done this way, chances are that the length is too short, spacers cannot be used and GPIB_CONN1 likely creates a short circuit on the metallic USB ports of the RPi.

![grafik](https://user-images.githubusercontent.com/25632350/93868475-c6f8aa00-fcca-11ea-9a4c-08c701dd070e.png)

When done wrong, desoldering the 40 pin header is painful...

**Comment by elektronomikon** [comment]
Hi,
thanks for the input - i extended the assembly instructions accordingly.
have fun,
Thomas
