### ISSUE TITLE
ID_SD ID_SC Connections

### ISSUE THREAD

**Issue by scentedcandle42** [elektronomikon/raspi_gpib_shield#4]
These connections (viewed on the pdf schematic) do not appear to connect anywhere on the schematic. Is this correct?

[https://github.com/elektronomikon/raspi_gpib_shield/blob/master/Documentation/RPi_GPIB_Shield.pdf]

**Comment by elektronomikon** [comment]
Hi,

Yes, this is correct.

ID_SD and ID_SC are I²C Bus 0, used internally on the RaspberryPi. They are generally marked as reserved, so that a custom hat does not interfere with the booting process.

have fun,
Thomas
