### ISSUE TITLE
Schematic PDF out of date

### ISSUE THREAD

**Issue by WhatIsTheFrequency** [elektronomikon/raspi_gpib_shield#5]
R19, R1 and R2 are shown on the PDF but have been replaced by R22, R24 and R23 in version 0.6.

The out of date PDF was also sent with the assembly instructions for the kit of parts.

**Comment by elektronomikon** [comment]
Thank you very much for the heads up!

Please see the updated version:
https://github.com/elektronomikon/raspi_gpib_shield/blob/76772e7b8017ecd45feb5491619b0a94da0672b7/Documentation/Raspi_GPIB_V6.pdf

have fun,
Thomas
